In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import os
import sys
sys.path.append('../src')

from math_utils_QR_elimina import *

In [2]:
# Generate random matrix
A = np.random.rand(10, 5)
h,R = thin_QR(A)

In [3]:
h

[array([0.83806786, 0.28104171, 0.06221366, 0.27741345, 0.08377366,
        0.10040811, 0.07068015, 0.18779732, 0.22039556, 0.17858197]),
 array([ 0.75710998,  0.2562113 ,  0.00627546,  0.38559286,  0.27574133,
         0.33066734, -0.03191738, -0.15744465, -0.03517536]),
 array([ 0.71132915, -0.18461712, -0.32651152,  0.07114371, -0.27071027,
         0.47773269, -0.21306106, -0.03672294]),
 array([ 0.8911341 , -0.20536484, -0.01102551, -0.05178454,  0.29766039,
         0.14389742, -0.22714298]),
 array([ 0.94704991,  0.02520695,  0.05640582,  0.14977725, -0.02726469,
        -0.2758675 ])]

In [4]:
R

array([[-2.09914351e+00, -1.34744751e+00, -1.34645849e+00,
        -1.22913552e+00, -1.59583068e+00],
       [-7.27092321e-17, -1.38269349e+00, -3.95181369e-01,
        -5.37444757e-01, -4.30007218e-01],
       [-6.28545420e-17, -1.18731919e-16, -9.02023306e-01,
        -3.24838222e-01, -2.68418102e-01],
       [-2.14692711e-16, -1.26549182e-16, -5.12334241e-18,
        -5.33326783e-01,  3.53684857e-01],
       [ 8.01946528e-17,  2.00980357e-16,  6.08376419e-18,
         0.00000000e+00, -8.06617608e-01],
       [-9.96701351e-17, -9.98478867e-17,  1.93889844e-19,
         0.00000000e+00,  6.93889390e-18],
       [-5.17955166e-17, -7.75521494e-17, -5.49214050e-17,
         0.00000000e+00,  1.38777878e-17],
       [ 3.90083219e-17,  4.25813310e-17, -9.35892820e-19,
         0.00000000e+00,  2.77555756e-17],
       [ 1.14739098e-16,  8.18871439e-17, -9.68455498e-19,
         0.00000000e+00, -6.93889390e-18],
       [ 6.44198716e-17, -6.76382801e-17, -1.22323785e-19,
         0.00000000e+00

In [5]:
apply_householders_matrix(h, R)

array([[0.84955586, 0.26022236, 0.37810934, 0.06116195, 0.98689989],
       [0.98883105, 0.741593  , 0.97665286, 0.81075694, 0.4496518 ],
       [0.21889561, 0.6557749 , 0.40735648, 0.22119867, 0.46312476],
       [0.97606521, 0.5453026 , 0.34052207, 0.71197189, 0.46980207],
       [0.29475337, 0.96802001, 0.15751676, 0.3355735 , 0.79796782],
       [0.35328084, 0.76993358, 0.58691354, 0.49158512, 0.41383679],
       [0.24868453, 0.82790499, 0.14461504, 0.40599774, 0.14109233],
       [0.66075538, 0.29342707, 0.9660561 , 0.62779426, 0.96605362],
       [0.77545064, 0.09314374, 0.01509868, 0.24365329, 0.37753251],
       [0.62833161, 0.26892797, 0.28349225, 0.00925528, 0.25354953]])

In [6]:
A

array([[0.84955586, 0.26022236, 0.37810934, 0.06116195, 0.98689989],
       [0.98883105, 0.741593  , 0.97665286, 0.81075694, 0.4496518 ],
       [0.21889561, 0.6557749 , 0.40735648, 0.22119867, 0.46312476],
       [0.97606521, 0.5453026 , 0.34052207, 0.71197189, 0.46980207],
       [0.29475337, 0.96802001, 0.15751676, 0.3355735 , 0.79796782],
       [0.35328084, 0.76993358, 0.58691354, 0.49158512, 0.41383679],
       [0.24868453, 0.82790499, 0.14461504, 0.40599774, 0.14109233],
       [0.66075538, 0.29342707, 0.9660561 , 0.62779426, 0.96605362],
       [0.77545064, 0.09314374, 0.01509868, 0.24365329, 0.37753251],
       [0.62833161, 0.26892797, 0.28349225, 0.00925528, 0.25354953]])

In [7]:
# Create vector of dimension m X 1
b = np.random.rand(10, 1)
b.shape

(10, 1)

In [8]:
apply_householders_vector(h, b)

array([[-1.57670354],
       [-0.91237323],
       [-0.38036856],
       [ 0.12431884],
       [-0.15145526],
       [ 0.21838579],
       [-0.10035443],
       [-0.20515446],
       [ 0.27559014],
       [ 0.89183011]])

In [10]:
apply_householders_matrix(h, b)

array([[ 0.74198394],
       [-0.13481341],
       [-0.20824165],
       [ 0.89184034],
       [ 0.08032182],
       [ 0.49618551],
       [ 0.09519678],
       [ 0.31442555],
       [ 0.88535989],
       [ 1.38591393]])