In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import os
import sys
sys.path.append('../src')

from math_utils_QR_elimina import *

In [2]:
# Generate random matrix
A = np.random.rand(10, 5)
h,R = thin_QR(A)

In [3]:
h

[array([0.73297523, 0.15544004, 0.30996458, 0.0615215 , 0.18229405,
        0.35025369, 0.09751193, 0.22521842, 0.22423372, 0.26888907]),
 array([ 0.83657646, -0.13091906,  0.00116601,  0.178528  , -0.36897552,
         0.07675661, -0.09998057,  0.07976363, -0.30452185]),
 array([ 0.72605528,  0.4818757 , -0.36209454, -0.16861593, -0.05095462,
        -0.06953775,  0.09645234, -0.25369437]),
 array([ 0.89605095, -0.21102807, -0.18113452,  0.17712771,  0.16120544,
        -0.23429396, -0.08657397]),
 array([ 0.85221796, -0.04905565, -0.03010098, -0.49854675,  0.08687509,
         0.11964896])]

In [4]:
R

array([[-1.93393738e+00, -1.76590853e+00, -1.59761126e+00,
        -1.44424529e+00, -1.38596668e+00],
       [-1.99478469e-16, -1.19958078e+00, -6.18263364e-01,
        -1.21037913e+00, -6.39150952e-01],
       [-4.51784567e-17,  1.44353648e-17, -1.01515676e+00,
        -2.34437197e-01, -1.13264406e-01],
       [-1.02945044e-16,  1.79027847e-17, -1.03187627e-16,
        -8.42236320e-01, -8.07155883e-01],
       [-7.41099274e-17,  9.38258755e-17, -4.94488562e-17,
        -8.61717327e-17, -6.71159946e-01],
       [-1.44975987e-16,  1.00113514e-16, -1.28495200e-17,
         8.15559618e-18,  0.00000000e+00],
       [-3.51225678e-17, -2.27503783e-17, -5.66148817e-17,
         5.00434631e-18,  0.00000000e+00],
       [-8.95911613e-17, -4.64858315e-17, -7.28015073e-17,
         2.73732092e-17,  0.00000000e+00],
       [-9.65819970e-17, -2.52462860e-17,  8.48999766e-17,
         4.10679989e-17,  1.38777878e-17],
       [-7.02172854e-17,  1.48360964e-16,  2.22583020e-17,
         7.86370475e-18

In [5]:
apply_householders(h, R)

array([[0.14408874, 0.65851389, 0.68676444, 0.99020013, 0.77198168],
       [0.44068128, 0.99363743, 0.53123441, 0.85493047, 0.4107059 ],
       [0.87876706, 0.76248773, 0.9170878 , 0.25409861, 0.14398457],
       [0.17441691, 0.2058316 , 0.90300612, 0.51859263, 0.63282742],
       [0.51681391, 0.9612845 , 0.1762883 , 0.76639378, 0.8631821 ],
       [0.99298895, 0.41795095, 0.54970749, 0.2760246 , 0.51472952],
       [0.27645182, 0.47659174, 0.28980998, 0.75429781, 0.66897168],
       [0.63850691, 0.54427353, 0.51992221, 0.83480563, 0.36936892],
       [0.63571524, 0.90177786, 0.90443457, 0.49914957, 0.3146876 ],
       [0.76231567, 0.27818944, 0.22195135, 0.30284184, 0.75189822]])

In [6]:
A

array([[0.14408874, 0.65851389, 0.68676444, 0.99020013, 0.77198168],
       [0.44068128, 0.99363743, 0.53123441, 0.85493047, 0.4107059 ],
       [0.87876706, 0.76248773, 0.9170878 , 0.25409861, 0.14398457],
       [0.17441691, 0.2058316 , 0.90300612, 0.51859263, 0.63282742],
       [0.51681391, 0.9612845 , 0.1762883 , 0.76639378, 0.8631821 ],
       [0.99298895, 0.41795095, 0.54970749, 0.2760246 , 0.51472952],
       [0.27645182, 0.47659174, 0.28980998, 0.75429781, 0.66897168],
       [0.63850691, 0.54427353, 0.51992221, 0.83480563, 0.36936892],
       [0.63571524, 0.90177786, 0.90443457, 0.49914957, 0.3146876 ],
       [0.76231567, 0.27818944, 0.22195135, 0.30284184, 0.75189822]])